name: open_mail_app
version: 0.4.5
homepage:

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.homex.open_mail_app
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin
